/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSocialRouteImport } from './routes/_app.social'
import { Route as AppSkuRouteImport } from './routes/_app.sku'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMarketplacesRouteImport } from './routes/_app.marketplaces'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppBudgetsRouteImport } from './routes/_app.budgets'
import { Route as AppBloggersRouteImport } from './routes/_app.bloggers'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSkuRoute = AppSkuRouteImport.update({
  id: '/sku',
  path: '/sku',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplacesRoute = AppMarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppBloggersRoute = AppBloggersRouteImport.update({
  id: '/bloggers',
  path: '/bloggers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/bloggers': typeof AppBloggersRoute
  '/budgets': typeof AppBudgetsRoute
  '/calendar': typeof AppCalendarRoute
  '/marketplaces': typeof AppMarketplacesRoute
  '/profile': typeof AppProfileRoute
  '/sku': typeof AppSkuRoute
  '/social': typeof AppSocialRoute
  '/tasks': typeof AppTasksRoute
  '/api/ai-chat': typeof ApiAiChatRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/bloggers': typeof AppBloggersRoute
  '/budgets': typeof AppBudgetsRoute
  '/calendar': typeof AppCalendarRoute
  '/marketplaces': typeof AppMarketplacesRoute
  '/profile': typeof AppProfileRoute
  '/sku': typeof AppSkuRoute
  '/social': typeof AppSocialRoute
  '/tasks': typeof AppTasksRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/bloggers': typeof AppBloggersRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/marketplaces': typeof AppMarketplacesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sku': typeof AppSkuRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/tasks': typeof AppTasksRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/bloggers'
    | '/budgets'
    | '/calendar'
    | '/marketplaces'
    | '/profile'
    | '/sku'
    | '/social'
    | '/tasks'
    | '/api/ai-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/bloggers'
    | '/budgets'
    | '/calendar'
    | '/marketplaces'
    | '/profile'
    | '/sku'
    | '/social'
    | '/tasks'
    | '/api/ai-chat'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/bloggers'
    | '/_app/budgets'
    | '/_app/calendar'
    | '/_app/marketplaces'
    | '/_app/profile'
    | '/_app/sku'
    | '/_app/social'
    | '/_app/tasks'
    | '/api/ai-chat'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sku': {
      id: '/_app/sku'
      path: '/sku'
      fullPath: '/sku'
      preLoaderRoute: typeof AppSkuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplaces': {
      id: '/_app/marketplaces'
      path: '/marketplaces'
      fullPath: '/marketplaces'
      preLoaderRoute: typeof AppMarketplacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bloggers': {
      id: '/_app/bloggers'
      path: '/bloggers'
      fullPath: '/bloggers'
      preLoaderRoute: typeof AppBloggersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBloggersRoute: typeof AppBloggersRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppMarketplacesRoute: typeof AppMarketplacesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSkuRoute: typeof AppSkuRoute
  AppSocialRoute: typeof AppSocialRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBloggersRoute: AppBloggersRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppMarketplacesRoute: AppMarketplacesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSkuRoute: AppSkuRoute,
  AppSocialRoute: AppSocialRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAiChatRoute: ApiAiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
